### ISSUE TITLE
Incorrect positioning of tiles

### ISSUE THREAD

**Issue by aap007** [lax20attack/destiny-dashboard#9]
Hi,

I saw your post on Reddit, and I am really interested in your webapp. Very nice project, I am sure to be going using it a lot!

While looking around i noticed a bug that is positioning a tile outside the canvas. This only happens with two specific widths of the canvas; around 1552px and around 1901px. I included two screenshots.

I am using Windows 7, Google Chrome version 60.0.3112.113 (64-bit)

Let me know if any help is desired.

![image](https://user-images.githubusercontent.com/10104857/30049792-39ef3d52-921c-11e7-8e9f-aec37b7ae87e.png)

![image](https://user-images.githubusercontent.com/10104857/30049817-4cdaccce-921c-11e7-9e46-f161a26b492c.png)

**Comment by lax20attack** [comment]
Hey, Thanks a lot for reporting! Unfortunately this is related to a bug in Material so there's not much I can do to fix it. It's actually caused by the gap to the left of the Stats card, so if you can re-position some things it should be good.

Here's the Material issue:
https://github.com/angular/material2/issues/4515

**Comment by aap007** [comment]
Thanks for responding,

I am at work right now, I will look in the issue Monday and maybe I can help solving it in the Material plugin.

First I am going to play Destiny 2 till Monday. Thanks again in creating this app and have fun in Destiny 2!
